---
title: "Install"
format: html
editor: visual
minimal: true
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
vignette: >
  %\VignetteIndexEntry{Install}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

For manual installation, an [R](https://www.r-project.org/) version \>= 4.4.0 is
required.

# Install packages required for metabonaut tutorials

Notes: only a development version of metabonaut is available as of now but a
stable version will come soon.

The following packages need to be installed for proper functioning of the
tutorials:

Run the code as follow:

```{r eval=FALSE}
install.packages("BiocManager")
BiocManager::install(c('RCurl', 'xcms', 'MsExperiment', 'SummarizedExperiment',
    'Spectra', 'MetaboCoreUtils', 'limma', 'matrixStats', 'pander', 
    'RColorBrewer', 'pheatmap', 'vioplot', 'ggfortify', 'gridExtra', 
    'AnnotationHub', 'CompoundDb', 'MetaboAnnotation', 
    'RforMassSpectrometry/MsIO', 'RforMassSpectrometry/MsBackendMetaboLights'))
```

# Docker image

The vignettes files along with an R runtime environment including all required
packages and the RStudio (Posit) editor are all bundled in a *docker* container.

After installation, this docker container can be run on the computer and the
code and examples from the vignettes can be evaluated within this environment
(without the need to install any additional packages or files).

-   If you don't already have, install [docker](https://www.docker.com/). Find
    installation information [here](https://docs.docker.com/desktop/).
-   Get the [docker
    image](https://hub.docker.com/r/rformassspectrometry/metabonaut) of this
    tutorial e.g. from the command line with
    `docker pull rformassspectrometry/metabonaut:latest`.
-   Start the docker container, either through the Docker Desktop, or on the
    command line with

```         
docker run -e PASSWORD=bioc -p 8787:8787 rformassspectrometry metabonaut:latest
```

-   Enter [`http://localhost:8787`](http://localhost:8787) in a web browser and
    log in with username `rstudio` and password `bioc`.
-   In the RStudio server version: open any of the R-markdown (*.Rmd*) files in
    the *vignettes* folder and evaluate the R code blocks in that document.
